#!/bin/bash

set -e

# Clean old package configuration files
packages=`dpkg -l | awk '/^rc/{ print $2}'`
#dpkg -l | awk '/^rc/{ print $2}' | xargs dpkg --purge
if [[ $packages == "" ]]
then
  echo "No old configurations found"
else
  xargs dpkg --purge $packages
  echo "Finished cleaning"
fi
