#!/bin/bash

set -e

# Clean old package configuration files
packages=`dpkg -l | awk '/^rc/{ print $2}'`
if [[ $packages == "" ]]
then
  echo "No old configurations found"
else
  dpkg -l | awk '/^rc/{ print $2}' | xargs dpkg --purge
  echo "Finished cleaning"
fi
