#!/bin/bash

set -e

green='\e[0;32m'
white='\e[0;37m'
red='\e[0;31m'
yellow='\e[0;33m'

if [ -z "$SUDO_USER" ]
then
  U=$USER
  su=""
else
  U=$SUDO_USER
  su="sudo -u $U -H"
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
target=$(readlink -f "$DIR")

home_dir=$(getent passwd "$U" | cut -d: -f 6)


# Check required packages
required=""
dpkg -l | grep rake > /dev/null
if [[ ! $? -eq 0 ]]
then
  required="$required rake"
fi
dpkg -l | grep curl > /dev/null
if [[ ! $? -eq 0 ]]
then
  required="$required curl"
fi
dpkg -l | grep vim > /dev/null
if [[ ! $? -eq 0 ]]
then
  required="$required vim"
fi

if [[ $require != "" ]]
then
  echo -e "${red}Missing package(s): $required${white}"
fi

echo -e "${green}Installing janus vim${white}"

if [[ ! -f $home_dir/.vim/installed ]]
then
  echo -e "${yellow}$su curl -Lo- http://bit.ly/janus-bootstrap | $su bash${white}"
  $su curl -Lo- http://bit.ly/janus-bootstrap | $su bash
  echo -e "${yellow}$su touch $home_dir/.vim/installed${white}"
  $su touch $home_dir/.vim/installed
fi

echo -e "${green}Linking vim configuration files${white}"
terminal_directories=("vim/colors")

for terminal_directory in "${terminal_directories[@]}"
do
  if [ -h $home_dir/.$terminal_directory ]
  then
    echo -e "${yellow} rm $home_dir/.$terminal_directory${white}"
    rm $home_dir/.$terminal_directory
  elif [ -d $home_dir/.$terminal_directory ]
  then
    echo -e "${yellow} mv $home_dir/.$terminal_directory $home_dir/.$terminal_directory.old${white}"
    mv $home_dir/.$terminal_directory $home_dir/.$terminal_directory.old
  fi
  echo -e "${yellow}$su ln -s $target/../../terminal_directories/$terminal_directory $home_dir/.$terminal_directory${white}"
  $su ln -s $target/../../terminal_directories/$terminal_directory $home_dir/.$terminal_directory
done
