#!/bin/bash

set -e

white='\e[1;37m'

echo "${white}cd $HOME/myubuntu"
cd $HOME/myubuntu
echo "${white}git fetch"
git fetch
echo "${white}git merge origin/master"
git merge origin/master
echo "${white}apply-terminal"
apply-terminal
