#!/bin/bash

white='\e[0;37m'
yellow='\e[0;33m'

# Default VM name is test
if [ "$1" == "" ]
then
  H="test"
else
  H=$1
fi

#
# Default OS is precise32
# For now I have the following list of boxes:
#   centos6
#   debian32
#   lucid32
#   precise32
#   precise64
#
if [ "$2" == "" ]
then
  OS="precise32"
else
  OS=$2
fi

echo -e "${yellow}mkdir -p $H/chef/site-cookbooks${white}"
mkdir -p $H/chef/site-cookbooks
echo -e "${yellow}cd $H${white}"
cd $H
echo -e "${yellow}vagrant init $OS${white}"
vagrant init $OS
echo -e "${yellow}Adding chef folders ...${white}"
git submodule add https://github.com/phunehehe/chef-cookbooks.git chef/chef-cookbooks
git submodule add ssh://git@gitlab.cogini.com:1026/phunehehe/chef-repo.git chef/chef-repo
mkdir -p chef/site-cookbooks/main
